repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix, --show-fixes]
-   repo: https://github.com/samueljsb/sort-lines
    rev: v0.3.0
    hooks:
    -   id: sort-lines
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: ['-p', '.*[^0-9a-z-_/.=].*']
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-mock-methods
