name: dependencies

on:
  pull_request:
    paths:
    - pyproject.toml
    - requirements*
  push:
    branches: [main]

# Only allow one instance of this workflow for each PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version-file: '.github/workflows/.python-version'
        cache: 'pip'
    - run: python -m pip install uv
    - run: uv pip compile --output-file=requirements.txt --group=dev pyproject.toml
    - run: git diff --color=always --exit-code
